version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: student-management-db
    environment:
      POSTGRES_DB: student_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - student-management-network
    restart: unless-stopped

  # Spring Boot Application
  app:
    build: .
    container_name: student-management-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - postgres
    networks:
      - student-management-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  student-management-network:
    driver: bridge 